[font]
  normal = { family = "Caskaydia Cove Nerd Font", style = "Regular" }
  bold = { family = "Caskaydia Cove Nerd Font", style = "Bold" }
  italic = { family = "Caskaydia Cove Nerd Font", style = "Italic" }

[window]
  opacity = 0.7
